"use client";
import { Ban, Download, FileText, Plus, X } from "lucide-react";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { PageHeading } from "@/components/ui/page-heading";
import { StatusBadge } from "@/components/ui/status-badge";
import { ApiError, apiRequest } from "@/lib/api";

type Receipt = { id:string; orden_id:string; sucursal_nombre:string; tipo:string; serie:string; numero:number; estado:string; cliente_nombre:string; cliente_documento:string; moneda:string; total:string; emitido_at:string; motivo_anulacion:string|null };
type Order = { id:string; numero:number; sucursal_nombre:string; cliente_nombre:string; cliente_documento:string; total:string };
const money=(v:string)=>`S/ ${Number(v).toFixed(2)}`; const msg=(e:unknown)=>e instanceof ApiError?e.message:"Ocurrió un error";
export function ComprobantesModule(){
 const [receipts,setReceipts]=useState<Receipt[]>([]),[orders,setOrders]=useState<Order[]>([]); const [modal,setModal]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(""); const [orderId,setOrderId]=useState(""),[type,setType]=useState("boleta"),[notes,setNotes]=useState("");
 const load=useCallback(async()=>{try{const [a,b]=await Promise.all([apiRequest<Receipt[]>("/comprobantes"),apiRequest<Order[]>("/comprobantes/ordenes-disponibles")]);setReceipts(a);setOrders(b);}catch(e){setError(msg(e));}},[]);
 useEffect(()=>{const t=setTimeout(()=>void load(),0);return()=>clearTimeout(t)},[load]);
 async function create(e:FormEvent){e.preventDefault();setSaving(true);try{await apiRequest("/comprobantes",{method:"POST",body:JSON.stringify({orden_id:orderId,tipo:type,observaciones:notes||null})});setModal(false);setOrderId("");await load();}catch(x){setError(msg(x));}finally{setSaving(false)}}
 async function cancel(r:Receipt){const motivo=prompt("Motivo de anulación:");if(!motivo)return;try{await apiRequest(`/comprobantes/${r.id}/anular`,{method:"POST",body:JSON.stringify({motivo})});await load()}catch(e){setError(msg(e))}}
 return <div className="space-y-5"><PageHeading title="Comprobantes internos" subtitle="Emite constancias en PDF para órdenes completamente pagadas." action={<button className="button primary" disabled={!orders.length} onClick={()=>setModal(true)}><Plus size={16}/>Emitir comprobante</button>}/>
 <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800"><strong>Importante:</strong> estos documentos son constancias internas y no tienen validez tributaria ante SUNAT.</div>
 {error?<div className="flex justify-between rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}<button onClick={()=>setError("")}><X size={16}/></button></div>:null}
 <div className="grid gap-3 sm:grid-cols-3"><Metric label="Emitidos" value={receipts.filter(r=>r.estado==="emitido").length}/><Metric label="Anulados" value={receipts.filter(r=>r.estado==="anulado").length}/><Metric label="Pendientes de emisión" value={orders.length}/></div>
 <section className="overflow-hidden rounded-xl border bg-white shadow-sm">{!receipts.length?<Empty/>:receipts.map(r=><div key={r.id} className="grid gap-3 border-b p-4 md:grid-cols-[150px_1fr_130px_auto]"><div><strong>{r.serie}-{String(r.numero).padStart(8,"0")}</strong><div className="text-xs capitalize text-slate-500">{r.tipo.replace("_"," ")}</div></div><div><strong>{r.cliente_nombre}</strong><div className="text-xs text-slate-500">{r.cliente_documento} · {r.sucursal_nombre}</div></div><div><strong>{money(r.total)}</strong><div className="text-xs text-slate-400">{new Date(r.emitido_at).toLocaleString("es-PE")}</div></div><div className="flex items-center gap-2"><StatusBadge status={r.estado} label={r.estado}/><a className="button" target="_blank" href={`/api/backend/comprobantes/${r.id}/pdf`}><Download size={14}/></a>{r.estado==="emitido"?<button className="button text-red-600" onClick={()=>void cancel(r)}><Ban size={14}/></button>:null}</div></div>)}</section>
 {modal?<Modal close={()=>setModal(false)}><form className="space-y-4" onSubmit={create}><Field label="Orden pagada"><select required className="form-control" value={orderId} onChange={e=>setOrderId(e.target.value)}><option value="">Seleccionar</option>{orders.map(o=><option key={o.id} value={o.id}>OT-{String(o.numero).padStart(5,"0")} · {o.cliente_nombre} · {money(o.total)}</option>)}</select></Field><Field label="Tipo"><select className="form-control" value={type} onChange={e=>setType(e.target.value)}><option value="boleta">Boleta interna</option><option value="factura">Factura interna (requiere RUC)</option><option value="nota_venta">Nota de venta</option></select></Field><Field label="Observaciones"><textarea className="form-control min-h-20" value={notes} onChange={e=>setNotes(e.target.value)}/></Field><div className="flex justify-end gap-2 border-t pt-4"><button type="button" className="button" onClick={()=>setModal(false)}>Cancelar</button><button disabled={saving} className="button primary">{saving?"Emitiendo…":"Emitir"}</button></div></form></Modal>:null}</div>
}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-xl border bg-white p-4"><div className="text-2xl font-black">{value}</div><div className="text-xs text-slate-500">{label}</div></div>} function Empty(){return <div className="p-12 text-center text-sm text-slate-500"><FileText className="mx-auto mb-2"/>Aún no hay comprobantes.</div>} function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span className="mb-1 block text-xs font-semibold">{label}</span>{children}</label>} function Modal({close,children}:{close:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><div className="w-full max-w-lg rounded-2xl bg-white"><div className="flex justify-between border-b p-5"><h2 className="font-bold">Emitir comprobante</h2><button onClick={close}><X size={18}/></button></div><div className="p-5">{children}</div></div></div>}
