"use client";
import { Eye, History, Search, X } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { PageHeading } from "@/components/ui/page-heading";
import { ApiError, apiRequest } from "@/lib/api";
type Audit={id:string;usuario_nombre:string;accion:string;entidad:string;entidad_id:string|null;datos_anteriores:Record<string,unknown>|null;datos_nuevos:Record<string,unknown>|null;ip:string|null;created_at:string};
const msg=(e:unknown)=>e instanceof ApiError?e.message:"Ocurrió un error";
export function AuditoriaModule(){
 const [items,setItems]=useState<Audit[]>([]),[actions,setActions]=useState<string[]>([]),[entities,setEntities]=useState<string[]>([]),[action,setAction]=useState(""),[entity,setEntity]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[selected,setSelected]=useState<Audit|null>(null),[error,setError]=useState("");
 const load=useCallback(async()=>{try{const p=new URLSearchParams();if(action)p.set("accion",action);if(entity)p.set("entidad",entity);if(from)p.set("desde",new Date(`${from}T00:00:00`).toISOString());if(to)p.set("hasta",new Date(`${to}T23:59:59`).toISOString());setItems(await apiRequest<Audit[]>(`/auditoria?${p}`))}catch(e){setError(msg(e))}},[action,entity,from,to]);
 useEffect(()=>{const t=setTimeout(async()=>{try{const o=await apiRequest<{acciones:string[];entidades:string[]}>("/auditoria/opciones");setActions(o.acciones);setEntities(o.entidades);await load()}catch(e){setError(msg(e))}},0);return()=>clearTimeout(t)},[load]);
 return <div className="space-y-5"><PageHeading title="Auditoría" subtitle="Consulta quién realizó cada cambio importante dentro de la empresa."/>
 {error?<div className="flex justify-between rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}<button onClick={()=>setError("")}><X size={16}/></button></div>:null}
 <section className="grid gap-3 rounded-2xl border bg-white p-4 shadow-sm sm:grid-cols-2 xl:grid-cols-5"><select className="form-control" value={action} onChange={e=>setAction(e.target.value)}><option value="">Todas las acciones</option>{actions.map(x=><option key={x}>{x}</option>)}</select><select className="form-control" value={entity} onChange={e=>setEntity(e.target.value)}><option value="">Todas las entidades</option>{entities.map(x=><option key={x}>{x}</option>)}</select><input type="date" className="form-control" value={from} onChange={e=>setFrom(e.target.value)}/><input type="date" className="form-control" value={to} onChange={e=>setTo(e.target.value)}/><button className="button primary" onClick={()=>void load()}><Search size={15}/>Filtrar</button></section>
 <section className="overflow-hidden rounded-xl border bg-white shadow-sm">{!items.length?<div className="p-12 text-center text-sm text-slate-500"><History className="mx-auto mb-2"/>No hay movimientos para estos filtros.</div>:items.map(item=><button key={item.id} onClick={()=>setSelected(item)} className="grid w-full gap-3 border-b p-4 text-left text-sm hover:bg-slate-50 md:grid-cols-[160px_150px_1fr_42px]"><div><strong>{item.usuario_nombre}</strong><div className="text-xs text-slate-400">{new Date(item.created_at).toLocaleString("es-PE")}</div></div><div><span className="rounded-full bg-blue-50 px-2 py-1 text-xs font-semibold text-blue-700">{item.accion}</span></div><div><strong>{item.entidad.replaceAll("_"," ")}</strong><div className="font-mono text-[10px] text-slate-400">{item.entidad_id||"Sin identificador"}</div></div><Eye size={16} className="text-slate-400"/></button>)}</section>
 {selected?<Modal close={()=>setSelected(null)}><div className="grid gap-3 sm:grid-cols-2"><Info label="Usuario" value={selected.usuario_nombre}/><Info label="Acción" value={selected.accion}/><Info label="Entidad" value={selected.entidad}/><Info label="Fecha" value={new Date(selected.created_at).toLocaleString("es-PE")}/></div><Json title="Valores anteriores" value={selected.datos_anteriores}/><Json title="Valores nuevos" value={selected.datos_nuevos}/></Modal>:null}</div>
}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-3"><div className="text-[10px] font-bold uppercase text-slate-400">{label}</div><div className="mt-1 font-semibold capitalize">{value}</div></div>} function Json({title,value}:{title:string;value:Record<string,unknown>|null}){return <div className="mt-4"><h3 className="mb-2 text-sm font-bold">{title}</h3><pre className="max-h-64 overflow-auto rounded-xl bg-slate-950 p-4 text-xs text-slate-100">{value?JSON.stringify(value,null,2):"Sin información"}</pre></div>} function Modal({close,children}:{close:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><div className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white"><div className="flex justify-between border-b p-5"><h2 className="font-bold">Detalle de auditoría</h2><button onClick={close}><X size={18}/></button></div><div className="p-5">{children}</div></div></div>}
