import {
  Boxes,
  CalendarDays,
  ChartNoAxesCombined,
  ClipboardList,
  FileDown,
  Gauge,
  HardHat,
  Building2,
  ReceiptText,
  Users,
  ArrowLeftRight,
  Wrench,
  HandCoins,
  ClipboardCheck,
  UserCog,
  ShieldCheck,
  Settings,
  FileText,
  History,
  KeyRound,
} from "lucide-react";

export const navSections = [
  {
    label: "Principal",
    items: [
      { href: "/dashboard", label: "Dashboard", icon: Gauge, permission: "dashboard.ver" },
      { href: "/perfil", label: "Mi cuenta", icon: KeyRound, permission: "dashboard.ver" },
      { href: "/agenda", label: "Agenda / Bahías", icon: CalendarDays, permission: "agenda.ver" },
      { href: "/ordenes", label: "Órdenes de trabajo", icon: ClipboardList, badge: 3, permission: "ordenes.ver" },
    ],
  },
  {
    label: "Operaciones",
    items: [
      { href: "/cotizaciones", label: "Cotizaciones", icon: ReceiptText, permission: "cotizaciones.ver" },
      { href: "/inspecciones", label: "Inspecciones", icon: ClipboardCheck, permission: "inspecciones.ver" },
      { href: "/pagos", label: "Pagos", icon: HandCoins, permission: "pagos.ver" },
      { href: "/comprobantes", label: "Comprobantes", icon: FileText, permission: "comprobantes.ver" },
      { href: "/servicios", label: "Servicios", icon: Wrench, permission: "servicios.ver" },
      { href: "/inventario", label: "Inventario", icon: Boxes, permission: "inventario.ver" },
      { href: "/transferencias", label: "Transferencias", icon: ArrowLeftRight, permission: "transferencias.ver" },
    ],
  },
  {
    label: "Gestión",
    items: [
      { href: "/sucursales", label: "Sucursales", icon: Building2, permission: "sucursales.ver" },
      { href: "/empleados", label: "Empleados", icon: HardHat, permission: "empleados.ver" },
      { href: "/clientes", label: "Clientes", icon: Users, permission: "clientes.ver" },
      { href: "/usuarios", label: "Usuarios", icon: UserCog, permission: "usuarios.ver" },
      { href: "/roles", label: "Roles y permisos", icon: ShieldCheck, permission: "usuarios.ver" },
      { href: "/configuracion", label: "Configuración", icon: Settings, permission: "configuracion.ver" },
      { href: "/auditoria", label: "Auditoría", icon: History, permission: "auditoria.ver" },
      { href: "/estadisticas", label: "Estadísticas", icon: ChartNoAxesCombined, permission: "estadisticas.ver" },
      { href: "/reportes", label: "Reportes", icon: FileDown, permission: "reportes.ver" },
    ],
  },
] as const;

export const routeTitles: Record<string, string> = {
  "/dashboard": "Dashboard",
  "/perfil": "Mi cuenta",
  "/agenda": "Agenda / Bahías",
  "/ordenes": "Órdenes de trabajo",
  "/cotizaciones": "Cotizaciones",
  "/inspecciones": "Inspecciones",
  "/pagos": "Pagos",
  "/comprobantes": "Comprobantes",
  "/servicios": "Servicios",
  "/inventario": "Inventario",
  "/transferencias": "Transferencias",
  "/empleados": "Empleados",
  "/sucursales": "Sucursales",
  "/clientes": "Clientes",
  "/usuarios": "Usuarios",
  "/roles": "Roles y permisos",
  "/configuracion": "Configuración",
  "/auditoria": "Auditoría",
  "/estadisticas": "Estadísticas",
  "/reportes": "Reportes",
};
